"""SolarBackend protocol — shared interface for MCP transports."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..models import Override


@runtime_checkable
class SolarBackend(Protocol):
    """Operations exposed to MCP tools."""

    async def get_status(self) -> dict[str, Any]: ...

    async def get_health(self) -> dict[str, Any]: ...

    async def explain_decision(self, sections: str | None = None) -> dict[str, Any]: ...

    async def simulate_decision(self) -> dict[str, Any]: ...

    async def get_engine_config(self) -> dict[str, Any]: ...

    async def get_forecast(self) -> dict[str, Any]: ...

    async def get_plan(self) -> dict[str, Any]: ...

    async def get_grid_stats(self) -> dict[str, Any]: ...

    async def get_decision_history(self, limit: int) -> list[dict[str, Any]]: ...

    async def get_execution_history(self, limit: int) -> list[dict[str, Any]]: ...

    async def get_shed_history(self, limit: int) -> list[dict[str, Any]]: ...

    async def get_telemetry_window(self, hours: int) -> list[dict[str, Any]]: ...

    async def get_grid_events(self, days: int) -> list[dict[str, Any]]: ...

    async def get_shed_snapshots(self) -> dict[str, Any]: ...

    async def apply_override(self, ov: Override, *, confirm_kill_switch: bool) -> dict[str, Any]: ...

    async def clear_override(self) -> dict[str, Any]: ...

    async def trigger_cycle(self) -> dict[str, Any]: ...

    async def refresh_forecast(self) -> dict[str, Any]: ...

    async def update_config(self, patch: dict) -> dict[str, Any]: ...
