"""Generate and persist local admin credentials on the data volume."""

from __future__ import annotations

import re
import secrets
import shlex
from pathlib import Path

import bcrypt

LOCAL_AUTH_ENV_FILENAME = "local_auth.env"

_ENV_KEY_RE = re.compile(r"^([A-Z_][A-Z0-9_]*)=(.*)$")


def local_auth_env_path(data_dir: Path) -> Path:
    return data_dir / LOCAL_AUTH_ENV_FILENAME


def generate_password(length: int = 24) -> str:
    """Random password (alphanumeric, no /+= from base64)."""
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode()


def generate_session_secret() -> str:
    return secrets.token_hex(32)


def _unwrap_env_value(raw: str) -> str:
    """Strip one layer of shell quotes if present."""
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "'\"":
        return raw[1:-1]
    return raw


def read_env_value(path: Path, key: str) -> str | None:
    if not path.is_file():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _ENV_KEY_RE.match(line.strip())
        if match and match.group(1) == key:
            return _unwrap_env_value(match.group(2))
    return None


def write_local_auth_env(
    path: Path,
    *,
    username: str,
    password_hash: str,
    session_secret: str,
) -> None:
    """Write or upsert auth keys in local_auth.env (hash only, mode 0600).

    Values are shell-quoted so bcrypt hashes survive `run.sh` / env loaders
    that historically sourced the file with `.` (which expands `$2b$…`).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    updates = {
        "LOCAL_ADMIN_USERNAME": username,
        "LOCAL_ADMIN_PASSWORD_HASH": password_hash,
        "SESSION_SECRET": session_secret,
    }
    lines: list[str] = []
    seen: set[str] = set()
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            match = _ENV_KEY_RE.match(line.strip())
            if match:
                key = match.group(1)
                if key in updates:
                    lines.append(f"{key}={shlex.quote(updates[key])}")
                    seen.add(key)
                    continue
                if key == "LOCAL_ADMIN_PASSWORD":
                    continue
            lines.append(line)
    for key, value in updates.items():
        if key not in seen:
            lines.append(f"{key}={shlex.quote(value)}")
    header = "# Local admin credentials — generated by reset-local-password; do not commit"
    if not lines or not lines[0].startswith("#"):
        lines.insert(0, header)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
